api/pom.xml
CDI-509 Updating pom file to use latest felix plugin
split of PR #243 for better resolution tracking
=> CDI-509 Updating pom file to use latest felix plugin switch to version 2.5.4

api/pom.xml, api/src/main/java/javax/enterprise/inject/spi/BeanManager.java, api/src/main/java/javax/enterprise/inject/spi/ObserverMethod.java, api/src/main/java/javax/enterprise/inject/spi/Prioritized.java, spec/src/main/doc/events.asciidoc, spec/src/main/doc/spi.asciidoc
This PR replace #242 for tracking purpose. It targets the right branch. Comment in #242 are still accurate
=> CDI-4 and CDI-521 resolution

api/src/main/java/javax/enterprise/inject/spi/CDI.java, api/src/main/java/javax/enterprise/inject/spi/CDIProvider.java, spec/src/main/doc/cdi-se.asciidoc, spec/src/main/doc/cdi-spec.asciidoc
CDI-26 Adding API and spec content to support Java SE bootstrap
Discussion was on PR #243. This one only targets the right branch for better Jira tracking
=> CDI-26 Adding API and spec content to support Java SE bootstrap

api/src/main/java/javax/enterprise/inject/spi/ProcessObserverMethod.java, spec/src/main/asciidoc/core/spi.asciidoc
CDI-458 Give the possibility to deactivate an observer in ProcessObserverMethod
CDI-522 Create add method setObserver() to ProcessObserverMethod SPI event
=> CDI-458, CDI-522 deactivate an observer and add method setObserver() in ProcessObserverMethod

spec/src/main/asciidoc/core/events.asciidoc
Removing the sentence as we decided on F2F meeting.s
=> CDI-544 remove the sentence.

spec/src/main/asciidoc/core/events.asciidoc, spec/src/main/asciidoc/core/implementation.asciidoc, spec/src/main/asciidoc/javaee/events_ee.asciidoc
CDI-569 Add @ObservesAsync where the spec mention @Observes
=> CDI-569 Add @ObservesAsync where the spec mention @Observes

api/pom.xml, api/src/test/java/org/jboss/cdi/api/test/CDITest.java, api/src/test/java/org/jboss/cdi/api/test/DummyCDIProvider.java, api/src/test/java/org/jboss/cdi/api/test/DummyCDIProvider2.java
CDI-575 Add test for CDI class
Added test works in 1.2 and 2.0-EDR1 branches
=> CDI-575 Add test for CDI class

api/src/main/java/javax/enterprise/inject/spi/CDI.java, api/src/test/java/org/jboss/cdi/api/test/CDITest.java, api/src/test/java/org/jboss/cdi/api/test/DummyCDIProviderWithNullCDI.java
CDI-573 Review code of CDI class to switch to ServiceLoader
=> CDI-573 Review code of CDI class to switch to ServiceLoader

spec/src/main/asciidoc/core/injectionandresolution.asciidoc
CDI-586 Add spec text for new Literals
=> CDI-586 Add spec text for new Literals

spec/src/main/asciidoc/core/events.asciidoc
* https://issues.jboss.org/browse/CDI-494
* http://lists.jboss.org/pipermail/cdi-dev/2016-February/007789.html
=> CDI-494 Events - clarify a wildcard type is not an unresolvable type variable

api/src/main/java/javax/enterprise/inject/spi/AfterBeanDiscovery.java, api/src/main/java/javax/enterprise/inject/spi/AfterTypeDiscovery.java, api/src/main/java/javax/enterprise/inject/spi/BeforeBeanDiscovery.java, api/src/main/java/javax/enterprise/inject/spi/CDIProvider.java, api/src/main/java/javax/enterprise/inject/spi/ProcessAnnotatedType.java, api/src/main/java/javax/enterprise/inject/spi/ProcessBeanAttributes.java, api/src/main/java/javax/enterprise/inject/spi/ProcessInjectionPoint.java, api/src/main/java/javax/enterprise/inject/spi/ProcessObserverMethod.java, api/src/main/java/javax/enterprise/inject/spi/builder/AnnotatedConstructorConfigurator.java, api/src/main/java/javax/enterprise/inject/spi/builder/AnnotatedFieldConfigurator.java, api/src/main/java/javax/enterprise/inject/spi/builder/AnnotatedMethodConfigurator.java, api/src/main/java/javax/enterprise/inject/spi/builder/AnnotatedParameterConfigurator.java, api/src/main/java/javax/enterprise/inject/spi/builder/AnnotatedTypeConfigurator.java, api/src/main/java/javax/enterprise/inject/spi/builder/BeanAttributesConfigurator.java, api/src/main/java/javax/enterprise/inject/spi/builder/BeanConfigurator.java, api/src/main/java/javax/enterprise/inject/spi/builder/InjectionPointConfigurator.java, api/src/main/java/javax/enterprise/inject/spi/builder/ObserverMethodConfigurator.java, spec/src/main/asciidoc/cdi-spec.asciidoc, spec/src/main/asciidoc/core/spi.asciidoc
New PR for Configurators and Builders API
=> CDI-558 Standardize the Meta-Data builders API (BeanBuilder, etc...)

spec/src/main/asciidoc/core/spi.asciidoc
There are no such methods at InjectionPointConfigurator.
=> Correction of the new configurators text.

spec/src/main/asciidoc/core/inheritance.asciidoc
See [CDI-600] (https://issues.jboss.org/browse/CDI-600) for background.
=> CDI-600 clarify specialization code sample.

spec/src/main/asciidoc/core/spi.asciidoc
CDI-603 Create separate doc section for each Annotated*Configurator
=> CDI-603 Create separate doc section for each Annotated*Configurator

api/src/main/java/javax/enterprise/inject/spi/AfterTypeDiscovery.java, api/src/main/java/javax/enterprise/inject/spi/BeforeBeanDiscovery.java, api/src/main/java/javax/enterprise/inject/spi/builder/AnnotatedTypeConfigurator.java, spec/src/main/asciidoc/core/spi.asciidoc
add clarification for id
correct parameter switching
correct the spec that was wrong
=> CDI-620 Not clear what the id for an annotated type is.

spec/src/main/asciidoc/core/implementation.asciidoc
Fixed the example to use proper producer/disposer pattern for un-managed entity manager.
=> CDI-523 Use a proper entity manager that can be closed.

api/src/main/resources/beans_2_0.xsd
CDI-638 Introduce a new xsd for CDI 2.0
=> CDI-638 Introduce a new xsd for CDI 2.0

spec/src/main/asciidoc/core/decorators.asciidoc, spec/src/main/asciidoc/core/interceptors.asciidoc
Based on F2F feedback, clarifying what happens when its in both places.
=> CDI-490 Clarify what happens when an interceptor is enabled twice.

api/src/main/java/javax/enterprise/inject/se/SeContainerInitializer.java, spec/src/main/asciidoc/javase/bootstrap_se.asciidoc, spec/src/main/asciidoc/javase/javase.asciidoc, spec/src/main/asciidoc/javase/packagingdeployment_se.asciidoc
Comments and updates are welcome!! I think there is really room for further improvements.
=> SE part wording revision.

spec/src/main/asciidoc/core/definition.asciidoc, spec/src/main/asciidoc/core/packagingdeployment.asciidoc
<trim/> as discussed during the face2face meeting.
=> CDI-420 Introduce a way to discover all types but make only scope annotated classes eligible for bean

api/src/main/java/javax/enterprise/inject/spi/AnnotatedParameter.java
=> CDI-481 Introduce AnnotatedParameter.getJavaParameter()

api/src/main/java/javax/enterprise/inject/Instance.java, api/src/test/java/org/jboss/cdi/api/test/DummyCDIProvider.java, api/src/test/java/org/jboss/cdi/api/test/DummyCDIProvider2.java, spec/src/main/asciidoc/core/injectionandresolution.asciidoc
See also https://github.com/cdi-spec/cdi/pull/339.
=> CDI-651 Add convenient Instance.isResolvable()

spec/src/main/asciidoc/core/injectionandresolution.asciidoc
This PR attempts to reword the original proposal to better fit the spec terminology. The behavior should stay the same.
Changes from https://github.com/cdi-spec/cdi/pull/320 are also included.
=> CDI-627 Reword and include alternative stereotypes

spec/src/main/asciidoc/javase/bootstrap_se.asciidoc
I formatted service provider as a class, which is definitely wrong. Also it's better to start sentence with anything else than method name.
=> Update my previous wrong formatting and wording.

api/src/main/java/javax/enterprise/inject/spi/InjectionTargetFactory.java, spec/src/main/asciidoc/core/spi.asciidoc
CDI-643 Provide a way to easily configure injection point of an InjectionTarget
=> CDI-643 Provide a way to easily configure injection point of an InjectionTarget

api/src/main/java/javax/enterprise/inject/spi/CDI.java, api/src/main/java/javax/enterprise/inject/spi/CDIProvider.java, api/src/test/java/org/jboss/cdi/api/test/CDITest.java, api/src/test/java/org/jboss/cdi/api/test/DummyCDIProvider.java, api/src/test/java/org/jboss/cdi/api/test/DummyCDIProvider2.java, api/src/test/java/org/jboss/cdi/api/test/DummyCDIProviderWithNullCDI.java, spec/src/main/asciidoc/core/spi.asciidoc
CDI-655 Allow CDIProvider to specify the priority
=> CDI-655 Allow CDIProvider to specify the priority

spec/src/main/asciidoc/javaee/packagingdeployment_ee.asciidoc
This is first proposal and I am open to any suggestions.
=> CDI-667 introduce new chapter for trimmed bean archive in Java EE.

api/src/main/java/javax/enterprise/event/TransactionPhase.java, spec/src/main/asciidoc/core/events.asciidoc
I tried to reword the original PR from Mark to include the original suggestions.
=> CDI-578 reword original proposal.

api/src/main/java/javax/enterprise/inject/spi/configurator/ProducerConfigurator.java, spec/src/main/asciidoc/core/spi.asciidoc
CDI-673 Revisit manipulation with InjectionPoint(s) in ProducerConfigurator
Remove methods related to injectionPoints
=> CDI-673 Revisit manipulation with InjectionPoint(s) in ProducerConfigurator Remove methods related to injectionPoints

spec/src/main/asciidoc/core/packagingdeployment.asciidoc
If you don't want a PR for something this minor, I won't feel bad.
=> Spelling typo.

api/src/main/java/javax/enterprise/inject/spi/InterceptionFactory.java, spec/src/main/asciidoc/core/spi.asciidoc
CDI-670 Clarify InterceptionFactory.ignoreFinalMethods() purpose and functioning
=> CDI-670 Clarify InterceptionFactory.ignoreFinalMethods() purpose and functioning

api/src/main/java/javax/enterprise/inject/spi/InterceptionFactory.java, spec/src/main/asciidoc/core/spi.asciidoc
This PR is an attempt to improve the wording of `InterceptionFactory` javadoc. I realize that the proposed wording is not perfect. Still I think it's more understandable. Also few typos are fixed.
=> Improve InterceptionFactory wording

api/src/main/java/javax/enterprise/inject/se/SeContainer.java, api/src/main/java/javax/enterprise/inject/spi/BeanManager.java, api/src/main/java/javax/enterprise/inject/spi/CDI.java, spec/src/main/asciidoc/core/injectionandresolution.asciidoc, spec/src/main/asciidoc/core/spi.asciidoc, spec/src/main/asciidoc/javase/bootstrap_se.asciidoc
CDI-671 SPI element related to Instance are missing info about their qualifier
Adding rules regarding qualifier in different programmatic lookup situation
=> CDI-671 SPI element related to Instance are missing info about their qualifier

spec/src/main/asciidoc/core/decorators.asciidoc, spec/src/main/asciidoc/core/events.asciidoc, spec/src/main/asciidoc/core/inheritance.asciidoc, spec/src/main/asciidoc/core/spi.asciidoc
CDI-668 Most Example with @Priority provide non fully qualified constant name
=> CDI-668 Most Example with @Priority provide non fully qualified constant name

spec/src/main/asciidoc/core/definition.asciidoc, spec/src/main/asciidoc/core/implementation.asciidoc, spec/src/main/asciidoc/javaee/implementation_ee.asciidoc
illegal bean types in type set are ignored
=> CDI-495 What happens if an illegal bean type is found in the set of bean types

spec/src/main/asciidoc/core/spi.asciidoc
CDI-681 Spec doesn't talk about BeanConfigurator.read method
=> CDI-681 Spec doesn't talk about BeanConfigurator.read method

api/src/main/java/javax/enterprise/inject/Instance.java, spec/src/main/asciidoc/core/injectionandresolution.asciidoc
Added missing "@since" mention in Java doc as well
=> CDI-692 isResolvable missing from 5.6.1

spec/src/main/asciidoc/core/implementation.asciidoc
remove the invalid link:: macro prefix
=> fix broken link

api/src/main/java/javax/enterprise/inject/spi/ProcessBean.java
Fix https://issues.jboss.org/browse/CDI-737.
=> Update the referenced class in the return tag of the `ProcessBean#getAnnotated` method.

.travis.yml, api/pom.xml, pom.xml, release-utils.sh, spec/pom.xml
Changing GAV for Jakarta EE.
Usage of Jakarta EE staging repo for EL and Interceptor API (please use -Pstaging when building)
Publication targeted to Jakarta EE repository.
=> CDI-738 Generate Jakarta EE version of CDI API

api/pom.xml, api/src/main/java/javax/enterprise/inject/spi/WithAnnotations.java, pom.xml, spec/pom.xml
change repository access to SSL
=> Update to secure https access

spec/pom.xml
Signed-off-by: Ehsan Zaery Moghaddam <zaerymoghaddam@gmail.com>
=> Fixed parent version number in cdi-spec pom file

api/pom.xml, pom.xml, spec/pom.xml
align parent groupid to `jakarta.enterprise`
=> Fix parent groupid

api/pom.xml, pom.xml, spec/pom.xml
Signed-off-by: Scott M Stark <starksm64@gmail.com>
=> Update the parent groupId to jakarta.enterprise

spec/src/main/asciidoc/core/decorators.asciidoc, spec/src/main/asciidoc/core/injectionandresolution.asciidoc, spec/src/main/asciidoc/core/interceptors.asciidoc, spec/src/main/asciidoc/core/packagingdeployment.asciidoc
Signed-off-by: hantsy <hantsy@gmail.com>
=> chore(docs): update namespaces

api/src/main/resources/beans_3_0.xsd
Signed-off-by: hantsy <hantsy@gmail.com>
=> chore(api): fix a quotation marks error in beans.xsd

spec/src/main/asciidoc/core/events.asciidoc
=> [Issue-457] Observer resolution - assignability clarification

spec/src/main/asciidoc/core/packagingdeployment.asciidoc
Signed-off-by: Thiago Henrique Hupner <thihup@gmail.com>
=> Fix XML descriptor in documentation example

spec/src/main/asciidoc/core/events.asciidoc
=> Replace BeanManager#getEvents with reference to BeanContainer.

api/pom.xml
Signed-off-by: Scott M Stark <starksm64@gmail.com>
=> Move to final versions of dependencies for 4.0.0 final

spec/src/main/asciidoc/architecture.asciidoc
=> Remove duplicate phrase

README.md
GH Pages link was incorrect after repo migration.
=> Correct GH Pages link in README

.github/workflows/ci-actions.yml, api/src/main/java/jakarta/decorator/package-info.java, api/src/main/java/jakarta/enterprise/context/package-info.java, api/src/main/java/jakarta/enterprise/event/Observes.java, api/src/main/java/jakarta/enterprise/event/package-info.java, api/src/main/java/jakarta/enterprise/inject/spi/package-info.java
=> Address the javadoc errors under jdk17

api/pom.xml
=> Update to EE 11 final api dependencies

api/pom.xml, api/src/main/resources/beans_4_1.xsd, el/pom.xml, ide-config/pom.xml, lang-model/pom.xml, pom.xml, spec/pom.xml, spec/src/main/asciidoc/preface.asciidoc
=> Add a beans_4_1.xsd file and prepare to replace the staged 4.1.0 api jar.
