- api/src/main/java/javax/enterprise/event/Event.java
- spec/src/main/asciidoc/core/events.asciidoc
CDI-563 Event.fireAsync() - clarify the usage of the returned CompletionStage
> CDI-563 Event.fireAsync() - clarify the usage of the returned CompletionStage

- api/src/main/java/javax/enterprise/inject/Specializes.java
- api/src/main/java/javax/enterprise/inject/TransientReference.java
- api/src/main/java/javax/enterprise/inject/Vetoed.java
- api/src/main/java/javax/enterprise/inject/literal/InjectLiteral.java
- api/src/test/java/org/jboss/cdi/api/test/AnnotationLiteralTest.java
- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
- Inject, Vetoed, Specializes, TransientReference
- also polish the spec wording
> CDI-588 More literals for built-in annotations

- api/src/main/java/javax/enterprise/inject/Instance.java
- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
- dependent bean instances must be obtained by the same Instance object
> CDI-519 Instance.destroy() clarification

- api/src/main/java/javax/enterprise/inject/spi/ProcessAnnotatedType.java
- api/src/main/java/javax/enterprise/inject/spi/ProcessBeanAttributes.java
- api/src/main/java/javax/enterprise/inject/spi/ProcessInjectionPoint.java
- api/src/main/java/javax/enterprise/inject/spi/ProcessObserverMethod.java
- spec/src/main/asciidoc/core/spi.asciidoc
An IllegalStateException is thrown
> CDI-596 ProcessAnnotatedType - clarify what happens if both setAnnotatedType() and configurator are used within observer notification

- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
This is for fixing a backward-incompatible change we introduced in CDI-1.1.
The whole reason for verifying the <class> entries is to ensure that a user
doesn't have typos or list classes which do not exists or are no
'candidates' for being an Alternative at least.
So it's all about preventing user errors. Disallowing to veto() @Alternative
classes (which was perfectly allowed in CDI-1.0) was overreaching.
> CDI-627 also re-enable the rules of CDI-1.0

- api/src/main/java/javax/enterprise/inject/Instance.java
- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
Introduces `stream()` and `parallelStream()` methods for bean instances.
> CDI-636 Introduce the ability to stream bean instances, as well as parallel stream them.

- api/src/main/java/javax/enterprise/inject/spi/configurator/InjectionPointConfigurator.java
- spec/src/main/asciidoc/core/spi.asciidoc
I consider them completely useless. Please prove if I am wrong and demonstrate some nice use case when it could be useful.
> CDI-614 remove InjectionPointConfigurator read methods.

- api/src/main/java/javax/enterprise/context/BeforeDestroyed.java
- api/src/main/java/javax/enterprise/context/Destroyed.java
- api/src/test/java/org/jboss/cdi/api/test/AnnotationLiteralTest.java
- spec/src/main/asciidoc/core/scopescontexts.asciidoc
- spec/src/main/asciidoc/javaee/scopescontext_ee.asciidoc
- add @BeforeDestroyed and @AfterDestroyed
- deprecate @Destroyed
> CDI-625 Make it clear when exactly are context init/destroy events fired

- api/src/main/java/javax/enterprise/inject/spi/EventContext.java
- api/src/main/java/javax/enterprise/inject/spi/ObserverMethod.java
- spec/src/main/asciidoc/core/events.asciidoc
- spec/src/main/asciidoc/core/spi.asciidoc
https://issues.jboss.org/browse/CDI-592
I'm not 100% sure this is the best solution but I haven't found anything better.
This PR also introduces a new interface: `EventContext` which represents a context of a fired event (payload and metadata). I like this concept more than adding just another method parameter because it's easily extensible.
NOTE: If we go this way (introduce `EventContext`) we may also simplify `ObserverMethodConfigurator` which currently contains two versions of `notifyWith()`.
> CDI-592 Add overloader ObserverMethod.notify()

- spec/src/main/asciidoc/core/scopescontexts.asciidoc
A proposed clarification for CDI-634.
I am not sure if we should place this in section `6.5.4. Contextual reference validity` (as proposed here) since it is generally valid for both, EE and SE. Or if it should go into SE part of the doc.
Feel free to suggest && comment.
> CDI-634 clarify contextual ref. validity.

- api/src/main/java/javax/enterprise/event/Event.java
- api/src/main/java/javax/enterprise/event/ImmutableNotificationOptions.java
- api/src/main/java/javax/enterprise/event/NotificationOptions.java
- api/src/test/java/org/jboss/cdi/api/test/event/NotificationOptionsTest.java
- spec/src/main/asciidoc/core/events.asciidoc
https://issues.jboss.org/browse/CDI-650
> CDI-650 Introduce asynchronous event notification options

- api/src/main/java/javax/enterprise/inject/spi/EventContext.java
- api/src/main/java/javax/enterprise/inject/spi/ObserverMethod.java
- api/src/main/java/javax/enterprise/inject/spi/configurator/ObserverMethodConfigurator.java
- spec/src/main/asciidoc/core/spi.asciidoc
- accepts EventContext
- there is no need to define two notifyWith() methods anymore
- allows to throw checked exceptions within a callback
> CDI-612 Introduce EventConsumer

- api/src/main/java/javax/enterprise/inject/spi/BeforeBeanDiscovery.java
- spec/src/main/asciidoc/core/spi.asciidoc
CDI-642 Allow defining interceptor binding or qualifier with an AnnotatedTypeConfigurator
> CDI-642 Allow defining interceptor binding or qualifier with an AnnotatedTypeConfigurator

- api/src/main/java/javax/enterprise/inject/spi/ProcessBean.java
- api/src/main/java/javax/enterprise/inject/spi/ProcessSyntheticBean.java
- spec/src/main/asciidoc/core/spi.asciidoc
- also introduce `ProcessSyntheticBean` (allows to filter custom bean impls added through `AfterBeanDiscovery.addBean()`)
> CDI-439 Clarify ProcessBean.getAnnotated()

- api/src/main/resources/beans_2_0.xsd
Attempt to define `trim` in beans_2_0.xsd. This should be just an empty element if I am not wrong.
> CDI-420 define trim also in beans xsd.

- spec/src/main/asciidoc/core/spi.asciidoc
Deprecate fireEvent() method more explictly in spec doc
> CDI-633 Deprecate fireEvent() method more explictly in spec doc

- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
I'm not going to fix the javadoc because we don't mention resolving ambiguities for any method there. I think to specify this only in the spec text.
> CDI-662 Fix Instance.isResolvable() text

- spec/src/main/asciidoc/core/spi.asciidoc
CDI-677 Specify the default scope for beans created from BeanConfigurator
> CDI-677 Specify the default scope for beans created from BeanConfigurator

- spec/src/main/asciidoc/core/scopescontexts.asciidoc
- spec/src/main/asciidoc/javaee/scopescontext_ee.asciidoc
Clarify in core when request context is active, and change verbiage a bit to align to common term of context.
> CDI-690 Request Context Clarification

- api/src/main/java/javax/enterprise/util/AnnotationLiteral.java
- api/src/main/java/javax/enterprise/util/SecurityActions.java
- api/src/test/java/org/jboss/cdi/api/test/privileged/annotation/AnnotationLiteralTest.java
- api/src/test/java/org/jboss/cdi/api/test/privileged/annotation/MyAnnotation.java
- api/src/test/java/org/jboss/cdi/api/test/privileged/annotation/MyAnnotationLiteral.java
Addition of privileged bloc in AnnotationLiteral
> CDI-699 AnnotationLiteral should use privileged actions for reflective operations

- api/pom.xml
prevent adding files to source jar from folder target/test-classes with absolute path
currently source jar files contains entries with absolute path (entries starting with /) which does not make sense and causes failure of javadocs referencing cdi-api-2.0.SP1-sources.jar
0  07-13-2018 18:18   /
0  05-27-2018 08:56   /Users/
0  07-19-2018 16:31   /Users/antoine/
0  06-26-2018 14:05   /Users/antoine/dev/
0  06-16-2017 09:09   /Users/antoine/dev/cdi/
0  07-19-2018 16:31   /Users/antoine/dev/cdi/cdi-spec/
0  07-19-2018 16:31   /Users/antoine/dev/cdi/cdi-spec/api/
0  07-19-2018 16:31   /Users/antoine/dev/cdi/cdi-spec/api/target/
0  07-19-2018 16:31   /Users/antoine/dev/cdi/cdi-spec/api/target/test-classes/
0  01-04-2017 17:34   /Users/antoine/dev/cdi/cdi-spec/api/target/test-classes/META-INF/ …
> use testRources for filtering of src/test/resources in cdi-api

- api/pom.xml
An attempt to fix jenkins crash
see https://issues.apache.org/jira/browse/SUREFIRE-1588
> Configure surefire to fix crash on security manager tests

- api/src/main/java/jakarta/enterprise/inject/spi/CDI.java
- api/src/test/java/org/jboss/cdi/api/test/CDITest.java
- api/src/test/java/org/jboss/cdi/api/test/ClosableCDIProvider.java
Check for both IllegalStateException and null value when filtering discovered providers.
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>
> Check configuredProvider that it holds valid CDI container.

- api/pom.xml
- api/src/main/java/jakarta/enterprise/inject/spi/SessionBeanType.java
Recent merge of [some of the missing changes from 3.0 branch](https://github.com/eclipse-ee4j/cdi/commit/7a55f23bcd0d901a336d8b4b6dc0402c486c7368#diff-8658bb96fff6ac848cd28d3242fce067) caused re-introduction of EJB dependency when it is only really needed for Javadoc. I have bumped into this when building a shaded jar javadoc containing CDI API which now requires me to add EJB dep as well.
This PR removes EJB dep and only introduces it as additional javadoc dependency.
> Add EJB dependency only as JavaDoc dep.

- api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java
- api/src/main/java/jakarta/enterprise/inject/spi/BeanManager.java
- api/src/main/java/jakarta/enterprise/inject/spi/CDI.java
This is a first version of the Lite variant of BM - related to https://github.com/eclipse-ee4j/cdi/issues/469
It contains a subset of methods from original BM that would be guaranteed to run under CDI Lite restrictions all the while giving user an API that doesn't return `UnsupportedException` on any of its methods.
Note that the idea is that Lite users would be encouraged to use this Lite BM variant but they won't be blocked from using full blown `BeanManager` if they choose to (but some methods will throw exceptions). This is due to the fact that implementations can choose to implement more functionalities than Lite requires.
Any future changes that would want to add more methods from classic BM to its Lite counterpart are an easy change so I propose this first draft with smaller set of …
> Draft Lite version of BeanManager.

- api/src/main/java/jakarta/enterprise/inject/spi/EventMetadata.java
This is an oversight from https://github.com/eclipse-ee4j/cdi/pull/473 where the wording was incorrectly changed.
The only case in which `null` was to be returned was `BM.fireEvent()`.
We even had a TCK that asserted just that, see https://github.com/eclipse-ee4j/cdi-tck/blob/3.0.2/impl/src/main/java/org/jboss/cdi/tck/tests/event/metadata/EventMetadataTest.java
> Correction to wording of EventMetadata#getInjectionPoint

- api/src/main/java/jakarta/enterprise/inject/se/SeContainer.java
A new method called getBeanContainer() was added to the CDI type. For consistency this PR adds the same method to the SeContainer interface.
> Add getBeanContainer() method to SeContainer for consistency

- api/src/main/java/jakarta/enterprise/util/AnnotationLiteral.java
`AnnotationLiteral` eagerly initializes the reflective state of annotations. This state may not be needed if the implementation does not use reflection to access annotation literal members. This change makes this intialization lazy to avoid always initializing this state.
> Make AnnotationLiteral lazy

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/ClassConfig.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/DeclarationConfig.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Discovery.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Enhancement.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/ExactType.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/FieldConfig.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/InjectionPointInfo.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/MethodConfig.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/ObserverInfo.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Processing.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/ScopeInfo.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SubtypesOf.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Synthesis.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticBeanBuilder.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticBeanCreator.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticBeanDisposer.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticComponents.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticObserver.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticObserverBuilder.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Types.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Validation.java
- api/src/main/java/jakarta/enterprise/lang/model/AnnotationMember.java
- api/src/main/java/jakarta/enterprise/lang/model/declarations/MethodInfo.java
- documentation added for synthetic beans and observers; this was
the last place where proper documentation was missing
- `DeclarationConfig` is no longer generic and `{Class,Method,Field}Config`
explicitly override the configuration methods, so that users don't have to
declare a useless type argument when using `DeclarationConfig`
- `AnnotationMember.as*` methods don't perform type conversions
- added `MethodInfo.isConstructor` to distinguish constructors
from regular methods
> improve extension API documentation and resolve some open questions

- spec/src/main/asciidoc/core/definition.asciidoc
> Allow using @Priority within stereotypes.

- api/src/main/java/jakarta/enterprise/inject/spi/configurator/BeanConfigurator.java
This is to allow setting a priority for synthetic beans created
using `BeanConfigurator`.
I briefly considered if `priority` should be added to
`BeanAttributesConfigurator` as well, but that would have
a ripple effect. It also doesn't reflect the present reality.
A custom `Bean` implementation can be added a priority
by implementing the `Prioritized` interface. Adding only
`BeanConfigurator.priority` is a perfect mirror of that
in the configurator API.
> add BeanConfigurator.priority

- api/src/main/java/jakarta/enterprise/inject/Instance.java
- api/src/test/java/org/jboss/cdi/api/test/ClosableCDIProvider.java
- api/src/test/java/org/jboss/cdi/api/test/DummyCDIProvider.java
- api/src/test/java/org/jboss/cdi/api/test/DummyCDIProvider2.java
- api/src/test/java/org/jboss/cdi/api/test/privileged/FakeCDIProvider.java
- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
Resolves #521 
BTW, I will also prepare a draft of a TCK test based on what we had in Weld.
> Programmatic lookup improvements, introduce Handle interface.

- spec/src/main/asciidoc/preface.asciidoc
Fixes #490 
A simple removal of TODO as discussed in the linked issue.
> Address the TODO in preface.

- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
- spec/src/main/asciidoc/core/injectionandresolution_full.asciidoc
Fixes #491 
I have rephrased the section so that it spell out a complete set of rules.
Furthermore, the notion of custom `Bean` implementation was moved from Lite section to Full and the corresponding TODO was erased.
> Address TODO in inter-module injection.

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/BuildCompatibleExtension.java
The language model API itself doesn't specify what annotations are
accessible. In the CDI context, only runtime-retained annotations
make sense, because that's the only way all implementation strategies
can be consistent. That's because:
- purely runtime implementations, such as Weld, only have access
to runtime-retained annotations;
- bytecode-based implementations, such as ArC, only have access
to runtime-retained and class-retained annotations, but don't
have access to source-retained annotations;
- annotation processing-based implementations, such as ODI, have
access to all annotations.
An alternative would be to specify that the language model _always_
returns only runtime-retained annotations. That would be just fine
strictly from the CDI perspective, but unforeseen cases may exist …
> Language model only returns runtime-retained annotations in build compatible extensions

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/BeanInfo.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/ObserverInfo.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticComponents.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticObserverBuilder.java
- lang-model/src/main/java/jakarta/enterprise/lang/model/AnnotationTarget.java
- lang-model/src/main/java/jakarta/enterprise/lang/model/declarations/ClassInfo.java
- lang-model/src/main/java/jakarta/enterprise/lang/model/declarations/MethodInfo.java
- lang-model/src/main/java/jakarta/enterprise/lang/model/types/WildcardType.java
- spec/src/main/asciidoc/core/spi_lite.asciidoc
- renamed `BeanInfo.getName()` to `name()` for consistency
- renamed `ObserverInfo.observedType()` to `eventType()` for clarity
- added `SyntheticComponents.addObserver(Type)` to allow registering
synthetic observers of parameterized types
- changed `WildcardType` representation to always include an upper
bound; the `? extends Object` type is no longer represented as `?`
because the upper bound may be annotated
- improved specification of `AnnotationTarget`, especially around
repeatable annotation types
- improved specification of `ClassInfo` and `MethodInfo`, especially
around implicit declarations and `abstract` classes/methods
> Language model and build compatible extensions API clarifications

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Discovery.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Enhancement.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/ScannedClasses.java
Fixes #564
I intentionally split this into 2 commits:
1. Make `@Enhancement(withAnnotations = {})` mean "no restriction on annotations". That is, types without annotations added through `@Discovery` may be subject to `@Enhancement`. The default is still `BeanDefiningAnnotations.class`.
2. Chagne the default value to an empty array, to align with Portable Extensions.
That's because I'm pretty sure we'd have a consensus on item 1, but not necessarily on item 2.
> Allow @Enhancement to not restrict the types based on annotations

- api/src/main/java/jakarta/enterprise/inject/Instance.java
The `Instance.handles()` method returns an `Iterable` of contextual
reference handles (`Instance.Handle<T>`). It used to be defined in
an invariant way (`Iterable<Handle<T>>`), which prevents CDI Lite
implementations from exposing subtypes of `Instance` and
`Instance.Handle` as public API. This commit changes the return
type to covariant `Iterable<? extends Handle<T>>`. With that change,
CDI Lite implementations can expose a `CustomInstance`, which extends
`Instance` and overrides the `Instance.handles()` method. The method,
in turn, can return `Iterable<CustomInstanceHandle<T>>`, where
`CustomInstanceHandle` extends `Instance.Handle`.
> Make the return type of Instance.handles() covariant

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Enhancement.java
The marker annotation `@Enhancement.BeanDefiningAnnotations`
used to represent all bean defining annotations for the purpose
of restricting the set of types on which `@Enhancement` should
be performed. That, however, is pretty useless: `@Enhancement`
is only performed on types that were discovered during type
discovery, and all such types have a bean defining annotation.
(Either they have it directly, or `@Dependent` is implied
in case of classes added through `@Discovery` that don't have
a bean defining annotation.)
> Remove Enhancement.BeanDefiningAnnotations

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/ScannedClasses.java
This is because `ScannedClasses` may be implemented on top of
Portable Extensions using `BeforeBeanDiscovery.addAnnotatedType`,
which doesn't specify what happens when the same identifier
is used multiple times, and doesn't provide a portable way
to "override" the type that was discovered by the container.
> Specify that duplicate type discovery is non-portable

- api/src/main/java/jakarta/enterprise/inject/spi/ObserverMethod.java
- spec/src/main/asciidoc/core/spi_full.asciidoc
Fixes #563 
I am deliberately keeping the return value for synth observers undefined because I understand some implementations can choose to return `null` but in Weld this is apparently never the case and instead synth. OMs belong to the extension declaring them.
> Add ObserverMethod#getDeclaringBean method.

- api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java
- api/src/main/java/jakarta/enterprise/inject/spi/BeanManager.java
> Move getInjectableReference method from BeanContainer to BeanManager

- spec/src/main/asciidoc/core/definition.asciidoc
- spec/src/main/asciidoc/core/definition_full.asciidoc
- spec/src/main/asciidoc/core/implementation.asciidoc
- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
- spec/src/main/asciidoc/core/lifecycle.asciidoc
- spec/src/main/asciidoc/core/scopescontexts.asciidoc
- spec/src/main/asciidoc/core/scopescontexts_full.asciidoc
When I was reviewing the remaining CDI 4.0 work, I realized we kept the session scope in CDI Lite. I believe it should be moved to CDI Full, because:
- the session scope is not actually defined at all in Core CDI
- the definition in CDI EE heavily relies on the Servlet API, which isn't even proposed to be part of the Jakarta EE 10 Core Profile (per https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE10CoreProfileRelasePlan)
- modern application architectures often don't rely on in-memory HTTP sessions at all (and we've deliberately left passivation out of Lite)
Hence, I'm proposing this PR to remove the session scope from Lite. It stays in Full.
> Move the session scope to CDI Full

- api/src/main/java/jakarta/enterprise/inject/spi/ObserverMethod.java
A follow up of PR - https://github.com/eclipse-ee4j/cdi/pull/578
Related to issue - #563 
Going over existing code, I realized that this would be a breaking change for any existing custom impl of `ObserverMethod`.
Making the method default and returning `null` will help avoid that, plus `null` is a valid return value for synthetic OMs anyway.
> Add default implementation of OM#getDeclaringBean()

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SkipIfPortableExtensionPresent.java
> Change parameter type of SkipIfPortableExtensionPresent from String to Class

- api/pom.xml
The package versions should be updated accordingly for this new release. At the moment, they were still on the same version as the CDI 3.0 release. Since this spec does not use semantic versioning, I have simply updated the major versions.
> Update package version

- api/pom.xml
- api/src/main/java/jakarta/enterprise/event/TransactionPhase.java
Fixes #608 
This is one of the ways to address it as we don't really need the dependency on JTA apart from javadoc of a single class.
(FYI @arjantijms)
> Remove dependency on JTA API

- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
This attempts to clarify the current specification of `Instance.iterator()`,
`Instance.stream()` and `Instance.handles()` in presence of dependency
ambiguity. My understanding is that this modification is what has always
been intended and how current implementations already work.
> Clarify ambiguity resolution during dynamic lookup

- spec/src/main/asciidoc/cdi-spec.asciidoc
- spec/src/main/asciidoc/core/core_structure.adoc
- spec/src/main/asciidoc/core/definition_full.asciidoc
- spec/src/main/asciidoc/preface.asciidoc
CDI specification up to version 3.0 used to have the sections numbered in a friendly way:
1. Architecture
2. Concepts
3. Programming model
And so on. With CDI 4.0 and the split to Lite and Full, sections were renumbered in a more ugly fashion:
1. Architecture
2. CDI Lite
2.1. Concepts
2.2. Programming model
4. CDI Full
Note that this numbering is different from the TCK Audit tool expectations and hence the TCK Audit reports are incorrect.
This commit restores the original numbering, which is more user-friendly and also conforms to the expectations of the TCK Audit tool.
> Improve section numbering

- docs/README.md
Before pointing out that the Ruby 2.x version could be the only one for running Jekyll, I think it is better to put it as a recommendation instead of a fact because doing fast research, it seems Jekyll could work with Rubby 3.x, but I didn't test it.
The second change relates to the URL, just added the final part.
> docs/README 

- lang-model/pom.xml
- pom.xml
Pragmatically speaking, the vendor neutral link will increase the odds that license scanners will correctly identify the license.
Philosophically speaking, the vendor neutral link reinforces the vendor neutral nature of the project.
> Use a vendor neutral link to the license text

- api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java
- api/src/main/java/jakarta/enterprise/inject/spi/ObserverMethod.java
- spec/src/main/asciidoc/core/events.asciidoc
- spec/src/main/asciidoc/core/implementation.asciidoc
- spec/src/main/asciidoc/core/inheritance_full.asciidoc
> Wording improvements

- api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java
Fixes #628 
I will also create tracking TCK issue.
Also, I've checked in Weld that this is indeed trivial to implement as all `BeanManager` instances hold references to all contexts anyway.
> Introduce BeanContainer.getContexts() to be able to get hold of all context objects, even if inactive

- api/src/main/java/jakarta/enterprise/util/AnnotationLiteral.java
> Improve AnnotationLiteral javadoc

- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
Fixes #649
This is a follow-up on #495 (#524, #527, #557). It doesn't add any new specification, merely adds information to one place that is already present on other places, for better internal consistency.
> Fix missing wording about priority on stereotypes

- api/pom.xml
- api/src/main/java/jakarta/enterprise/inject/spi/BeanManager.java
- api/src/main/java/jakarta/enterprise/inject/spi/EventMetadata.java
- el/pom.xml
- el/src/main/java/jakarta/enterprise/inject/spi/el/ELAwareBeanManager.java
- el/src/main/java/module-info.java
- el/src/main/javadoc/doc-files/speclicense.html
- el/src/main/javadoc/overview.html
- lang-model/pom.xml
- pom.xml
- spec/pom.xml
- spec/src/main/asciidoc/cdi-spec.asciidoc
- spec/src/main/asciidoc/core/events.asciidoc
- spec/src/main/asciidoc/core/spi_full.asciidoc
- spec/src/main/asciidoc/javaee/definition_ee.asciidoc
- spec/src/main/asciidoc/javaee/el.asciidoc
- spec/src/main/asciidoc/javaee/javaeeintegration.asciidoc
- spec/src/main/asciidoc/javaee/packagingdeployment_ee.asciidoc
- spec/src/main/asciidoc/javaee/spi_ee.asciidoc
- spec/src/main/asciidoc/preface.asciidoc
Fixes #613
The commits are best reviewed in isolation, and perhaps should be split into multiple PRs. Opening this one as a draft for discussion.
> Bump CDI version to 4.1 and place EL integration API in a new supplemental artifact

- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
We previously [1] changed the ambiguity resolution wording from
> The container eliminates all eligible beans that are not alternatives,
> except for producer methods and fields of beans that are alternatives.
to
> The container eliminates all eligible beans that are not alternatives
> selected for the application, except for producer methods and fields
> of beans that are alternatives.
At that time, we did _not_ add a rule to the CDI Full section that would
cover alternatives selected for the bean archive.
Note that for a bean to be _eligible_, it must be _available for injection_,
and an alternative is available for injection only if it is selected (for
application in CDI Lite; for application or for bean archive in CDI Full).
Alternative beans that are not selected are hence not even …
> Fix two small wording mistakes

- api/src/main/java/jakarta/enterprise/inject/spi/BeanManager.java
- spec/src/main/asciidoc/core/beanmanager_lite.asciidoc
- spec/src/main/asciidoc/core/spi_full.asciidoc
We previously [1] moved the `getInjectableReference()` from the `BeanContainer` interface to the `BeanManager` [2], but did not update the specification text accordingly. Thus, the method is specified in the CDI Lite part of the spec, but it in fact belongs to CDI Full. This commit moves the spec text around to fix that.
Additionally, this commit removes the declaration of `resolveObserverMethods()` from `BeanManager`, because that just overrides the same declaration that is present on `BeanContainer`.
Finally, this commit moves the declaration of `getInjectableReference()` from the end of the `BeanManager` source code to the beginning, for symmetry with the `BeanContainer` declaration and to restore the previous layout.
[1] https://github.com/jakartaee/cdi/commit/520bad1989101bf4523e13e8e …
> Move the specification of BeanManager.getInjectableReference() to CDI Full

- spec/src/main/asciidoc/core/beanmanager_lite.asciidoc
This is a follow up to #629 which added the method to the API, but didn't add a specification text.
> Add specification text for BeanContainer.getContexts()

- api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java
- api/src/main/java/jakarta/enterprise/inject/spi/BeanManager.java
The spec and TCK assert that `BeanContainer.createInstance()` must not be called before the `AfterDeploymentValidation` event is fired.
Correct some Javadoc which was inconsistent.
Fixes #688
> Fix Javadoc for createInstance validity

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/BuildServicesResolver.java
- api/src/main/java/jakarta/enterprise/inject/spi/CDI.java
We previously [1] added code to guard against repeated calls to these SPIs:
- `BuildServicesResolver.setBuildServices()`
- `CDI.setCDIProvider()`
The guards are unfortunately incorrect. This commit fixes them.
[1] https://github.com/jakartaee/cdi/commit/82ec5d71872212364a321cd3700d0ecadf9162d2
> Fix guards against repeated external sets of SPI implementations

- spec/src/main/asciidoc/core/definition.asciidoc
- spec/src/main/asciidoc/core/implementation.asciidoc
Sealed types are valid bean types, but they are unproxyable.
This commit only makes explicit what already implicitly follows from
the existing CDI specification and updates in the Java / JVM specifications.
> Specify behavior for sealed types

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/BeanInfo.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/InvokerInfo.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/Parameters.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticBeanBuilder.java
- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/SyntheticObserverBuilder.java
- api/src/main/java/jakarta/enterprise/inject/spi/ProcessManagedBean.java
- api/src/main/java/jakarta/enterprise/invoke/Invoker.java
- api/src/main/java/jakarta/enterprise/invoke/InvokerBuilder.java
- api/src/main/java/module-info.java
This PR has 2 commits with detailed commit messages. I'm copying the commit messages here for easier reference.
This PR doesn't include changes to the specification text, but the API javadocs are intentionally a specification-level material. There are several TODOs and everything is up for debate anyway, but I still wanted to provide something that is pretty well defined.
_`Invoker`_ is an indirect way of invoking a bean method. It is a simple
functional interface:
```java
interface Invoker<T, R> {
    R invoke(T instance, Object[] arguments);
}
```
Invokers are built using an _`InvokerBuilder`_. They must be thread-safe,
so frameworks can build an invoker for each relevant method once and then
reuse it to invoke that method whenever necessary.
An invoker may be built for a method that: …
> Method invokers

- api/src/main/java/jakarta/enterprise/inject/build/compatible/spi/BuildServicesResolver.java
- api/src/main/java/jakarta/enterprise/inject/spi/CDI.java
The `CDI.setCDIProvider()` method has been documented to throw `IllegalStateException` on repeated calls since version 1.0, but since version 2.0, the implementation in fact didn't honor this documentation. Multiple implementations started to silently depend on repeated `setCDIProvider()` calls being allowed, especially for testing.
We previously [1][2] fixed the implementation to actually do what it documents, planning to release the fix in CDI 4.1, but it turns out this is very inconvenient. Therefore, this commit makes repeated calls of `setCDIProvider()` officially allowed. For consistency, it also allows repeated calls of `BuildServicesResolver.setBuildServices()`.
[1] https://github.com/jakartaee/cdi/commit/82ec5d71872212364a321cd3700d0ecadf9162d2
[2] …
> Allow setting CDI SPI implementations repeatedly

- spec/src/main/asciidoc/core/implementation.asciidoc
Currently, the specification says that non-`@Dependent` beans may not have public fields. This is overly restrictive; in particular, implementing this rule precisely precludes passing the AtInject TCK, where `@Singleton` beans have public fields.
This commit relaxes the requirement: all pseudo-scoped beans may have public fields; normal scoped beans may not. This makes most sense, it is what all existing implementations do (checked ArC, Weld and OpenWebBeans) and it is how the TCK is already written.
Fixes #660
> Relax the scope requirement for public fields

- lang-model/pom.xml
- lang-model/src/main/java/jakarta/enterprise/lang/model/declarations/MethodInfo.java
This is a very minor fix for a typo in javadoc
> Fix typo in javadoc

- .github/workflows/ci-actions.yml
CI is still pointing towards `master` when we now have `main`.
We can also add newer JDK and update deps.
> Update CI setup - add JDK 21, bump versions on actions

- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
> Specify @Priority on producers

- spec/src/main/asciidoc/core/spi_full.asciidoc
Fixes #454 
This doesn't change functionality, just removes a bit of text potentially causing confusion.
While it is true that contexts aren't activated before this event, there is nothing preventing impls from activating them within this event. In fact, `BM#getReference` explicitly allows to resolve all beans at this point which means you have to be able to activate contexts anyway.
> Remove mention of context activation from AfterDeploymentValidation event

- api/pom.xml
- api/src/main/javadoc/overview.html
- el/pom.xml
- lang-model/pom.xml
- pom.xml
- spec/pom.xml
- spec/src/main/asciidoc/cdi-spec.asciidoc
- spec/src/main/asciidoc/license-asl2.asciidoc
- spec/src/main/asciidoc/license-final.asciidoc
+ Update to use latest parent pom for common plugin versions and sbom generation
+ Use parent pom version where appropriate
+ Update other plugin versions
+ Restore source attachment which was lost somewhere
+ Update copyright dates
> - Cleanup in prep for the 4.1.0-M1 release

- spec/src/main/asciidoc/architecture.asciidoc
- spec/src/main/asciidoc/core/implementation.asciidoc
- spec/src/main/asciidoc/core/lifecycle.asciidoc
> Updates for deprecation of the Managed Beans specification, #679

- api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java
- spec/src/main/asciidoc/core/beanmanager_lite.asciidoc
Fixes #498 
There was a request to have access to CDI assignability rules programmatically so this is the first thing coming to my mind.
**I am not 100% convinced that this feature is very useful (in that it can find some audience) so I would appreciate some feedback on whether we want to add it or not.**
Few notes:
* Delegate assignability is deliberately left out as I cannot imagine anyone extending that.
* The varargs argument for qualifiers might instead be a collection because there isn't really a case where this could be entirely left out due to presence of `@Default` - at least not the way it's worded right now as users are expected to list all required qualifiers.
* We could use the `TypesAndQualifiers` to also represent the event payload/qualifiers and injection point …
> Add API for programmatic access to assignability rules for observer methods and typesafe resolution.

- api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java
- spec/src/main/asciidoc/core/beanmanager_lite.asciidoc
Follow up to #700 with a few things I noticed while writing TCKs in jakartaee/cdi-tck#526:
* use code tags for true and false
* consistently use @ with annotation classes in javadoc
* fix wrong method name in spec
* add anchor name to spec
* no implied `Default` qualifier for events
* Change "beans and observers" to "beans and events" in spec for consistency
Relates to issue #498
> Tweaks to Bean and Event Assignability API

- api/src/main/java/jakarta/enterprise/inject/spi/BeanContainer.java
Follows up on a discussion in https://github.com/jakartaee/cdi-tck/pull/526
> Improve precision of the bean and event assignability API specification

- api/src/main/java/jakarta/enterprise/inject/spi/ProcessInjectionPoint.java
- api/src/main/java/jakarta/enterprise/inject/spi/ProcessInjectionTarget.java
- spec/src/main/asciidoc/javaee/spi_ee.asciidoc
> Remove references to the removed jakarta.annotation.ManagedBean #750

- api/pom.xml
Don't declare `overview.html` as a project resource. Instead have a separate `copy-resources` execution to copy and filter it.
Fixes #734
> Don't delcare overview.html as a resource so it doesn't get included in source jar

- api/pom.xml
- pom.xml
I missed this in #745 and maven outputs the following warning on every build:
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for jakarta.enterprise:jakarta.enterprise.cdi-api:jar:4.1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ line 382, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
> Set a version for the resources plugin

- CODE_OF_CONDUCT.md
- CONTRIBUTING.adoc
- NOTICE.md
- pom.xml
* Update the repository URLs in CONTRIBUTING
* List all the repositories in NOTICES
* Remove reference to `Signed-off-by` in CONTRIBUTING as it's [no longer required][no-sign-off]
* Add code of conduct file (looks like this wasn't previously required, but the handbook now says it [should be in every repo][coc-repo])
I noted a few things in these files that should be updated before I copy them over to the TCK repo.
[no-sign-off]: https://www.eclipse.org/lists/eclipse.org-committers/msg01291.html
[coc-repo]: https://www.eclipse.org/projects/handbook/#legaldoc-codeOfConduct
> Small corrections to project information files

- spec/src/main/asciidoc/core/injectionandresolution.asciidoc
We previously [1] changed wording in the ambiguity resolution specification from
> Return an `Iterator`, that iterates over the set of contextual references
> for the resulting beans and required type, as defined in <<contextual_reference>>.
to
> Return an `Iterator`, that iterates over the set of contextual references
> for the resulting beans, as defined in <<contextual_reference>>.
This was an attempt to simplify the text, but is in fact incorrect, because a contextual reference is always determined by the bean and the bean type.
This commit reverts to the previous wording.
[1] https://github.com/jakartaee/cdi/commit/74827d2808a4db73d1402206a8e116b5702d031a
> Revert incorrect change in ambiguity resolution

- spec/src/main/asciidoc/preface.asciidoc
> Update the changes spec section for 4.1

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/compatibility-certification-request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- api/pom.xml
- el/pom.xml
- ide-config/pom.xml
- lang-model/pom.xml
- pom.xml
- spec/pom.xml
> Move EE dependency version properties to parent pom

- .github/workflows/ci-actions.yml
JDK 11 build doesn't really work as we rely on EL API which has min JDK 17. Skipping just that module doesn't work either and build fails due to `module-info`.
> Remove JDK 11 from CI setup

- api/src/main/java/jakarta/enterprise/invoke/Invoker.java
- api/src/main/java/jakarta/enterprise/invoke/InvokerBuilder.java
The specification text is detailed enough, but we figured that adding slightly more text to the `Invoker` (and `InvokerBuilder`) javadoc can be helpful.
> Add slightly more details to the `Invoker` javadoc

- api/src/main/java/jakarta/enterprise/inject/se/SeContainerInitializer.java
- api/src/test/java/org/jboss/cdi/api/test/se/DummySeContainerInitializer.java
- api/src/test/java/org/jboss/cdi/api/test/se/DummySeContainerInitializer2.java
- spec/src/main/asciidoc/javase/bootstrap_se.asciidoc
Fixes #813 
Adds a new method to `SeContainerInitializer` which allows users to register build compatible extensions (BCE) without the need for discovery.
I am aware the `SeContainerInitializer` has [two variants of the `add` method for portable extensions (PE)](https://github.com/jakartaee/cdi/blob/4.1.0/api/src/main/java/jakarta/enterprise/inject/se/SeContainerInitializer.java#L192-L207), one of which allows you to pass in pre-initialized PE.
I intentionally skipped that for BCE as those were designed with stricter environments in mind. However, if there is need/want for this we can add it as well.
> Allow registering BCE in CDI SE without discovery

- api/pom.xml
- el/pom.xml
- ide-config/pom.xml
- lang-model/pom.xml
- pom.xml
- spec/pom.xml
We've already released 5.0.0.Alpha1. It makes no sense for the current version string to be 5.0.0.Alpha1-SNAPSHOT. We're currently working towards 5.0.0.Alpha2, so that should be reflected in the version.
> bump to 5.0.0.Alpha2-SNAPSHOT
